version: '3.4'

services:
  languagecardwithcontrollers:
    image: ${DOCKER_REGISTRY-}languagecardwithcontrollers
    build:
      context: .
      dockerfile: languagecardwithcontrollers/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.justyna.rule=Host(`justyna.localhost`)"
      - "traefik.http.routers.justyna.entrypoints=web"

  traefik:
    image: "traefik:v3.0"    
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  datastore:
    image: milesmcc/gcp-emulator
    environment:
      - DATASTORE_PROJECT_ID=langproject
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081